version: '3'

services:
  mongo:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - mongo:/data/db

  jsreport:
    image: jsreport/jsreport
    restart: always
    ports:
     - "5488:5488"
    volumes:
     - jsreport:/jsreport

  web:
    image: "mttstt/ictrisktool:${TAG}"
    ports:
     - "80:80"
    environment:
     - MONGO_URL=mongodb://mongo/ictrisktool
     - ROOT_URL=http://127.0.0.1
     - DELAY=5
     - passwdAD
    volumes:
     - ictrisktool:/tmp/files/lib

volumes:
   jsreport:
   ictrisktool:
   mongo:
